import {
  UtensilsCrossed,
  Coffee,
  Soup,
  IceCream,
  ShoppingBag,
  Shirt,
  Sparkles,
  Smartphone,
  Car,
  Bus,
  Train,
  CarFront,
  Fuel,
  Gamepad2,
  Film,
  Plane,
  Dumbbell,
  Home,
  Droplets,
  Heart,
  Pill,
  BookOpen,
  MonitorPlay,
  Gift,
  Wallet,
  Plus,
  ArrowLeft,
  Settings,
  BarChart3,
  User,
  FolderOpen,
  Store,
  Upload,
  Download,
  Calendar,
  PenTool,
  Mic,
  Search,
  Edit3,
  Trash2,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Check,
  Clock,
  ArrowRightLeft,
  Banknote,
  Trophy,
  TrendingUp,
  Briefcase,
  DollarSign,
  Coins,
  CreditCard,
  Users,
  Music,
  Stethoscope,
  FileText,
  PartyPopper,
  Layers,
  Landmark,
  RotateCcw,
} from 'lucide-react';

export const iconMap: Record<string, typeof UtensilsCrossed> = {
  expense: CreditCard,
  income: Banknote,
  transfer: ArrowRightLeft,
  borrow: Users,
  reimburse: FileText,
  refund: RotateCcw,
  deposit: Landmark,

  food: UtensilsCrossed,
  'food-breakfast': Coffee,
  'food-lunch': Soup,
  'food-dinner': UtensilsCrossed,
  'food-snack': IceCream,
  'food-takeout': Store,

  shopping: ShoppingBag,
  'shopping-clothes': Shirt,
  'shopping-daily': Sparkles,
  'shopping-electronics': Smartphone,
  'shopping-baby': Gift,
  'shopping-stationery': BookOpen,

  transport: Car,
  'transport-subway': Train,
  'transport-bus': Bus,
  'transport-taxi': CarFront,
  'transport-fuel': Fuel,
  'transport-travel': Plane,

  accommodation: Home,
  'accommodation-rent': Home,
  'accommodation-utility': Droplets,
  'accommodation-property': Layers,
  'accommodation-hotel': Landmark,

  study: BookOpen,
  'study-book': BookOpen,
  'study-course': MonitorPlay,
  'study-exam': FileText,
  'study-stationery': PenTool,

  social: PartyPopper,
  'social-gift': Gift,
  'social-party': Users,
  'social-entertainment': Film,
  'social-game': Gamepad2,

  beauty: Sparkles,
  'beauty-skincare': Heart,
  'beauty-makeup': Sparkles,
  'beauty-hair': Sparkles,

  travel: Plane,
  'travel-ticket': CreditCard,
  'travel-group': Users,
  'travel-shopping': ShoppingBag,

  medical: Stethoscope,
  'medical-hospital': Stethoscope,
  'medical-drug': Pill,
  'medical-checkup': Heart,

  membership: Film,
  'membership-video': Film,
  'membership-music': Music,
  'membership-fitness': Dumbbell,

  'other-expense': Gift,

  salary: Banknote,
  'salary-monthly': Banknote,
  'salary-bonus': Trophy,

  investment: TrendingUp,
  'investment-fund': TrendingUp,
  'investment-stock': DollarSign,
  'investment-deposit': Coins,

  'part-time': Briefcase,
  'part-time-freelance': Briefcase,
  'part-time-gig': DollarSign,

  'gift-income': Gift,
  'gift-income-redpacket': Wallet,
  'gift-income-birthday': Trophy,

  'other-income': Wallet,

  'transfer-out': ArrowRightLeft,
  'transfer-in': ArrowRightLeft,

  'borrow-lend': Users,
  'borrow-borrow': Users,
  'borrow-repay': ArrowRightLeft,

  'reimburse-apply': FileText,
  'reimburse-receive': Banknote,

  'refund-product': RotateCcw,
  'refund-service': RotateCcw,

  'deposit-savings': Coins,
  'deposit-investment': TrendingUp,

  plus: Plus,
  back: ArrowLeft,
  settings: Settings,
  stats: BarChart3,
  user: User,
  folder: FolderOpen,
  store: Store,
  upload: Upload,
  download: Download,
  calendar: Calendar,
  pen: PenTool,
  mic: Mic,
  search: Search,
  edit: Edit3,
  trash: Trash2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  clock: Clock,
  refresh: ArrowRightLeft,
};

export const getIcon = (iconName: string) => {
  return iconMap[iconName] || Gift;
};
