import {
  UtensilsCrossed,
  Coffee,
  Soup,
  IceCream,
  ShoppingBag,
  Shirt,
  Sparkles,
  Smartphone,
  Car,
  Bus,
  Train,
  CarFront,
  Fuel,
  Gamepad2,
  Film,
  Plane,
  Dumbbell,
  Home,
  Droplets,
  Wifi,
  Heart,
  Pill,
  BookOpen,
  MonitorPlay,
  Gift,
  Wallet,
  Plus,
  ArrowLeft,
  Settings,
  BarChart3,
  User,
  FolderOpen,
  Store,
  Upload,
  Download,
  Calendar,
  PenTool,
  Mic,
  Search,
  Edit3,
  Trash2,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Check,
  Clock,
  ArrowRightLeft,
} from 'lucide-react';

export const iconMap: Record<string, typeof UtensilsCrossed> = {
  food: UtensilsCrossed,
  'food-breakfast': Coffee,
  'food-lunch': Soup,
  'food-dinner': UtensilsCrossed,
  'food-snack': IceCream,
  shopping: ShoppingBag,
  'shopping-clothes': Shirt,
  'shopping-daily': Sparkles,
  'shopping-electronics': Smartphone,
  'shopping-beauty': Sparkles,
  transport: Car,
  'transport-bus': Bus,
  'transport-subway': Train,
  'transport-taxi': CarFront,
  'transport-fuel': Fuel,
  entertainment: Gamepad2,
  'entertainment-movie': Film,
  'entertainment-game': Gamepad2,
  'entertainment-travel': Plane,
  'entertainment-sport': Dumbbell,
  living: Home,
  'living-rent': Home,
  'living-water': Droplets,
  'living-internet': Wifi,
  medical: Heart,
  'medical-hospital': Heart,
  'medical-drug': Pill,
  study: BookOpen,
  'study-book': BookOpen,
  'study-course': MonitorPlay,
  other: Gift,
  'other-gift': Gift,
  'other-redpacket': Wallet,
  plus: Plus,
  back: ArrowLeft,
  settings: Settings,
  stats: BarChart3,
  user: User,
  folder: FolderOpen,
  store: Store,
  upload: Upload,
  download: Download,
  calendar: Calendar,
  pen: PenTool,
  mic: Mic,
  search: Search,
  edit: Edit3,
  trash: Trash2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  clock: Clock,
  refresh: ArrowRightLeft,
};

export const getIcon = (iconName: string) => {
  return iconMap[iconName] || Gift;
};
